
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'CHAR DIV LB MAIS MENOS MUL NUM PERCENTAGEM PONTO POTENCIA RBcont : NUM contcont : PONTO contcont : op contcont : emptyop : MAISop : MENOSop : MULop : DIVempty :'
    
_lr_action_items = {'NUM':([0,2,3,4,6,7,8,9,],[2,2,2,2,-5,-6,-7,-8,]),'PONTO':([0,2,3,4,6,7,8,9,],[3,3,3,3,-5,-6,-7,-8,]),'MAIS':([0,2,3,4,6,7,8,9,],[6,6,6,6,-5,-6,-7,-8,]),'MENOS':([0,2,3,4,6,7,8,9,],[7,7,7,7,-5,-6,-7,-8,]),'MUL':([0,2,3,4,6,7,8,9,],[8,8,8,8,-5,-6,-7,-8,]),'DIV':([0,2,3,4,6,7,8,9,],[9,9,9,9,-5,-6,-7,-8,]),'$end':([0,1,2,3,4,5,6,7,8,9,10,11,12,],[-9,0,-9,-9,-9,-4,-5,-6,-7,-8,-1,-2,-3,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'cont':([0,2,3,4,],[1,10,11,12,]),'op':([0,2,3,4,],[4,4,4,4,]),'empty':([0,2,3,4,],[5,5,5,5,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> cont","S'",1,None,None,None),
  ('cont -> NUM cont','cont',2,'p_cont_num','anaSin.py',25),
  ('cont -> PONTO cont','cont',2,'p_cont_ponto','anaSin.py',30),
  ('cont -> op cont','cont',2,'p_cont_op','anaSin.py',35),
  ('cont -> empty','cont',1,'p_cont_empty','anaSin.py',40),
  ('op -> MAIS','op',1,'p_op_sum','anaSin.py',46),
  ('op -> MENOS','op',1,'p_op_menos','anaSin.py',51),
  ('op -> MUL','op',1,'p_op_mul','anaSin.py',56),
  ('op -> DIV','op',1,'p_op_div','anaSin.py',61),
  ('empty -> <empty>','empty',0,'p_empty','anaSin.py',66),
]
